### ISSUE TITLE
Feature Request: treating aliased imports separately

### ISSUE THREAD

**Issue by dhrubabasu** [daixiang0/gci#175]
Thanks for the package, this solves nearly all our problems w.r.t. import sorting ❤️ 

What are your thoughts about treating aliased imports separately? (maybe through a separate config)

Feeding this to gci:
```golang
import (
	"context"

	"github.com/ava-labs/avalanchego/api/keystore"
	"github.com/ava-labs/avalanchego/database"
	"github.com/ava-labs/avalanchego/database/rpcdb"
	"github.com/ava-labs/avalanchego/vms/rpcchainvm/grpcutils"

	keystorepb "github.com/ava-labs/avalanchego/proto/pb/keystore"
	rpcdbpb "github.com/ava-labs/avalanchego/proto/pb/rpcdb"
)
```

yields:
```golang
import (
	"context"

	"github.com/ava-labs/avalanchego/api/keystore"
	"github.com/ava-labs/avalanchego/database"
	"github.com/ava-labs/avalanchego/database/rpcdb"
	keystorepb "github.com/ava-labs/avalanchego/proto/pb/keystore"
	rpcdbpb "github.com/ava-labs/avalanchego/proto/pb/rpcdb"
	"github.com/ava-labs/avalanchego/vms/rpcchainvm/grpcutils"
)
```

The gci config I'm using:
```yml
  gci:
    sections:
      - standard
      - default
      - blank
      - dot
      - prefix(github.com/ava-labs/avalanchego)
    skip-generated: true
    custom-order: true
```
